scene_number: 138 # REPLACE WITH DESIRED BENCHMARKING SCENE (look at ../scenes/metadata.json for available scenes)
spawn_location: # replace values with desired spawning location
  x: 0.0
  y: 0.0
  z: 0.0